# Generated by Django 3.0.4 on 2020-05-01 06:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('profile_pic', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('position', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('joined_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
