# Generated by Django 3.0.4 on 2020-05-01 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='players',
            name='profile_pic',
        ),
    ]
