# Generated by Django 3.0.4 on 2020-05-03 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_players_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='players',
            name='joined_date',
        ),
        migrations.AddField(
            model_name='players',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
